import React from "react";

import { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";

import { LoginForm } from "@/components/LoginForm";
import { RegisterForm } from "@/components/RegisterForm";

import { useAppSelector } from "@/redux/hooks";
import { selectUserData } from "@/redux/slices/user";

import { MainLayout } from "@/layouts/MainLayout";

import styles from "@/styles/Home.module.scss";

const Home: NextPage = () => {
  const [formType, setFormType] = React.useState<"login" | "register">("login");

  const userData = useAppSelector(selectUserData);

  const router = useRouter();

  React.useEffect(() => {
    userData && router.push("/posts");
  }, []);

  return (
    <>
      <Head>
        <title>Soundy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicons/favicon.ico" />
      </Head>
      <MainLayout hidden>
        <main className={styles.container}>
          <h1>
            Добро пожаловать в <span>Soundy</span>
          </h1>
          <div className={styles.formContainer}>
            {formType === "login" && (
              <LoginForm onOpenRegister={() => setFormType("register")} />
            )}
            {formType === "register" && (
              <RegisterForm onOpenLogin={() => setFormType("login")} />
            )}
          </div>
        </main>
      </MainLayout>
    </>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  if (ctx.req.cookies.authToken) {
    return {
      redirect: {
        destination: "/posts",
        permanent: false,
      },
    };
  }
  return {
    props: {},
  };
};
