import React from "react";

import { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";

import { MainLayout } from "@/layouts/MainLayout";

import { PageTitle } from "@/components/ui/PageTitle";
import { SearchInput } from "@/components/SearchInput";
import { ConversationItem } from "@/components/ConversationItem";
import { Line } from "@/components/ui/Line";

import { useAppSelector } from "@/redux/hooks";
import { selectUserData } from "@/redux/slices/user";

import { IConversation } from "@/api/types";

import styles from "./Conversations.module.scss";

const Conversations: NextPage = () => {
  const [searchText, setSearchText] = React.useState("");
  const [conversations, setConversations] = React.useState<IConversation[]>([
    {
      conversationId: "1",
      sender: {
        userId: "c0c07f9a-0b1e-45a9-9833-047be0f1c39d",
        login: "virtuux",
        name: "Иван",
        surname: "Данилов",
        birthDate: new Date("2004-03-18T15:27:10.000Z"),
        avatarUrl:
          "https://res.cloudinary.com/virtuux/image/upload/v1678860078/znfkvx9tp695zt5blze5.jpg",
        friends: [],
        playlist: [],
        friendRequests: [],
      },
      receiver: {
        userId: "c0c07f9a-0b1e-45a9-9833-047be0f1c39d",
        login: "virtuux",
        name: "Иван",
        surname: "Данилов",
        birthDate: new Date("2004-03-18T15:27:10.000Z"),
        avatarUrl:
          "https://res.cloudinary.com/virtuux/image/upload/v1678860078/znfkvx9tp695zt5blze5.jpg",
        friends: [],
        playlist: [],
        friendRequests: [],
      },
    },
    {
      conversationId: "2",
      sender: {
        userId: "c0c07f9a-0b1e-45a9-9833-047be0f1c39d",
        login: "virtuux",
        name: "Иван",
        surname: "Данилов",
        birthDate: new Date("2004-03-18T15:27:10.000Z"),
        avatarUrl:
          "https://res.cloudinary.com/virtuux/image/upload/v1678860078/znfkvx9tp695zt5blze5.jpg",
        friends: [],
        playlist: [],
        friendRequests: [],
      },
      receiver: {
        userId: "c0c07f9a-0b1e-45a9-9833-047be0f1c39d",
        login: "virtuux",
        name: "Иван",
        surname: "Данилов",
        birthDate: new Date("2004-03-18T15:27:10.000Z"),
        avatarUrl:
          "https://res.cloudinary.com/virtuux/image/upload/v1678860078/znfkvx9tp695zt5blze5.jpg",
        friends: [],
        playlist: [],
        friendRequests: [],
      },
    },
    {
      conversationId: "3",
      sender: {
        userId: "c0c07f9a-0b1e-45a9-9833-047be0f1c39d",
        login: "virtuux",
        name: "Иван",
        surname: "Данилов",
        birthDate: new Date("2004-03-18T15:27:10.000Z"),
        avatarUrl:
          "https://res.cloudinary.com/virtuux/image/upload/v1678860078/znfkvx9tp695zt5blze5.jpg",
        friends: [],
        playlist: [],
        friendRequests: [],
      },
      receiver: {
        userId: "c0c07f9a-0b1e-45a9-9833-047be0f1c39d",
        login: "virtuux",
        name: "Иван",
        surname: "Данилов",
        birthDate: new Date("2004-03-18T15:27:10.000Z"),
        avatarUrl:
          "https://res.cloudinary.com/virtuux/image/upload/v1678860078/znfkvx9tp695zt5blze5.jpg",
        friends: [],
        playlist: [],
        friendRequests: [],
      },
    },
    {
      conversationId: "4",
      sender: {
        userId: "c0c07f9a-0b1e-45a9-9833-047be0f1c39d",
        login: "virtuux",
        name: "Иван",
        surname: "Данилов",
        birthDate: new Date("2004-03-18T15:27:10.000Z"),
        avatarUrl:
          "https://res.cloudinary.com/virtuux/image/upload/v1678860078/znfkvx9tp695zt5blze5.jpg",
        friends: [],
        playlist: [],
        friendRequests: [],
      },
      receiver: {
        userId: "c0c07f9a-0b1e-45a9-9833-047be0f1c39d",
        login: "virtuux",
        name: "Иван",
        surname: "Данилов",
        birthDate: new Date("2004-03-18T15:27:10.000Z"),
        avatarUrl:
          "https://res.cloudinary.com/virtuux/image/upload/v1678860078/znfkvx9tp695zt5blze5.jpg",
        friends: [],
        playlist: [],
        friendRequests: [],
      },
    },
  ]);

  const userData = useAppSelector(selectUserData);

  const router = useRouter();

  return (
    <MainLayout fullWidth>
      <Head>
        <title>Сообщения</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicons/favicon.ico" />
      </Head>
      <main className={styles.container}>
        <PageTitle pageTitle="Сообщения" />
        <SearchInput handleChange={(text) => setSearchText(text)} width={600} />
        <div className={styles.conversationsBlock}>
          {conversations.map((obj) => (
            <>
              <ConversationItem
                key={obj.conversationId}
                {...obj}
                messages={[]}
              />
              {obj.conversationId !==
                conversations[conversations.length - 1]?.conversationId && (
                <Line />
              )}
            </>
          ))}
        </div>
      </main>
    </MainLayout>
  );
};

export default Conversations;

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  if (!ctx.req.cookies.authToken) {
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    };
  }
  return {
    props: {},
  };
};
