import React from "react";

import { GetServerSideProps, NextPage } from "next";
import Head from "next/head";

import { MainLayout } from "@/layouts/MainLayout";

import { PageTitle } from "@/components/UI/PageTitle";
import { SearchInput } from "@/components/UI/SearchInput";
import { BlueButton } from "@/components/UI/BlueButton";
import { UsersIcon } from "@/components/UI/Icons/UsersIcon";
import { PostIcon } from "@/components/UI/Icons/PostIcon";

import styles from "./Search.module.scss";
import { SearchedUsers } from "@/components/SearchedUsers";
import { Api } from "@/api/index";
import { IUser } from "@/api/types";

const Search: NextPage = () => {
  const [searchUserQuery, setSearchUserQuery] = React.useState("");
  const [isEmptyResults, setIsEmptyResults] = React.useState(false);
  const [searchedUsers, setSearchedUsers] = React.useState<IUser[]>([]);
  const [isLoading, setIsLoading] = React.useState(false);
  const [page, setPage] = React.useState(1);

  const searchUsers = React.useCallback(async () => {
    try {
      if (searchUserQuery && searchUserQuery !== " ") {
        setPage(1);

        setSearchedUsers([]);

        const splitSearchUsers = searchUserQuery.split(" ");

        if (splitSearchUsers.length === 2) {
          setIsLoading(true);

          const data = await Api().user.findUsers(
            {
              _name: splitSearchUsers[0],
              _surname: splitSearchUsers[1],
            },
            page
          );

          setSearchedUsers(data);

          setIsLoading(false);

          !data.length ? setIsEmptyResults(true) : setIsEmptyResults(false);
        } else if (splitSearchUsers.length === 1) {
          setPage(1);

          setIsLoading(true);

          const data = await Api().user.findUsers(
            {
              _query: splitSearchUsers[0],
            },
            page
          );

          setSearchedUsers(data);

          setIsLoading(false);

          !data.length ? setIsEmptyResults(true) : setIsEmptyResults(false);
        }
      }
    } catch (err) {
      console.warn(err);
    }
  }, [page, searchUserQuery]);

  return (
    <MainLayout fullWidth>
      <Head>
        <title>Поиск</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicons/favicon.ico" />
      </Head>
      <main className={styles.container}>
        <PageTitle pageTitle="Поиск" />
        <div className={styles.content}>
          <div>
            <SearchInput handleChange={(text) => setSearchUserQuery(text)} />
            <div className={styles.actions}>
              <BlueButton
                text="Найти"
                color="primary"
                handleClick={searchUsers}
              >
                <UsersIcon color="white" />
              </BlueButton>
              <BlueButton text="Найти" color="primary">
                <PostIcon color="white" />
              </BlueButton>
            </div>
          </div>
          <SearchedUsers
            searchUserQuery={searchUserQuery}
            handleLoading={(isLoading) => setIsLoading(isLoading)}
            isLoading={isLoading}
            handleSearchedUsers={(users) => setSearchedUsers(users)}
            searchedUsers={searchedUsers}
            handleChangeUsersPage={() => setPage((page) => page + 1)}
            page={page}
            isEmptyResults={isEmptyResults}
          />
        </div>
      </main>
    </MainLayout>
  );
};

export default Search;

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  if (!ctx.req.cookies.authToken) {
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    };
  }
  return {
    props: {},
  };
};
