import { NextPage, NextPageContext } from "next";
import React from "react";
import { Api } from "@/api/index";
import Head from "next/head";
import { WriteForm } from "@/components/WriteForm";

const Write: NextPage = () => {
  return (
    <>
      <Head>
        <title>Создание поста</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicons/favicon.ico" />
      </Head>
      <WriteForm />
    </>
  );
};

export default Write;

export const getServerSideProps = async (ctx: NextPageContext) => {
  try {
    const user = await Api(ctx).user.getMe();

    if (!user) {
      return {
        props: {},
        redirect: {
          destination: "/",
          permanent: false,
        },
      };
    }
    return {
      props: {},
    };
  } catch (err) {
    return {
      props: {},
      redirect: {
        destination: "/",
        permanent: false,
      },
    };
  }
};
